# Generated by Django 5.2.14 on 2026-09-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0002_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('organization_ids', models.JSONField(default=list)),
                ('state', models.CharField(default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('scheduled_key', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('approver_id_snapshot', models.BigIntegerField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=160)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('lines', models.JSONField(default=list)),
                ('adjustments', models.JSONField(blank=True, default=list)),
                ('excluded_ids', models.JSONField(blank=True, default=list)),
                ('recipients', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('artifact', models.BinaryField(default=bytes)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='ledger.batch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shifts.organization')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=24)),
                ('recipient', models.BigIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=160, unique=True)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.batch')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('input_type', models.CharField(choices=[('time', 'time'), ('quantity', 'quantity'), ('amount', 'amount'), ('mark', 'mark')], default='time', max_length=16)),
                ('frequency', models.CharField(choices=[('entry', 'entry'), ('daily', 'daily'), ('monthly', 'monthly')], default='entry', max_length=16)),
                ('sheet', models.CharField(blank=True, max_length=31)),
                ('sort_order', models.IntegerField(default=100)),
                ('included', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('legacy_code', models.CharField(blank=True, max_length=48)),
                ('default_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shifts.organization')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation', models.CharField(choices=[('fixed', 'fixed'), ('hourly', 'hourly'), ('quantity', 'quantity'), ('amount', 'amount')], default='fixed', max_length=16)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shifts.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.service')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shifts.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.service')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('day', models.PositiveSmallIntegerField(default=1)),
                ('hour', models.PositiveSmallIntegerField(default=10)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('service_chat', models.BigIntegerField(blank=True, null=True)),
                ('service_thread', models.BigIntegerField(blank=True, null=True)),
                ('expense_chat', models.BigIntegerField(blank=True, null=True)),
                ('expense_thread', models.BigIntegerField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.telegramcontact')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.BooleanField(default=False)),
                ('include_expenses', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shifts.organization')),
                ('excluded_services', models.ManyToManyField(blank=True, to='ledger.service')),
                ('recipients', models.ManyToManyField(blank=True, to='ledger.telegramcontact')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', 'service'), ('oneoff', 'oneoff'), ('expense', 'expense')], max_length=16)),
                ('employee_name', models.CharField(blank=True, max_length=160)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('units', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('review', models.BooleanField(default=False)),
                ('included', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('source', models.CharField(default='web', max_length=16)),
                ('author_id', models.BigIntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=160)),
                ('raw_text', models.TextField(blank=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('part', models.PositiveIntegerField(default=0)),
                ('legacy_kind', models.CharField(blank=True, max_length=16)),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('auto_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shifts.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shifts.organization')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.service')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('chat_id__isnull', False), ('message_id__isnull', False)), fields=('chat_id', 'message_id', 'part'), name='ledger_message_part'), models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('legacy_kind', 'legacy_id'), name='ledger_legacy_record')],
            },
        ),
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shifts.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'organization'), name='ledger_accrual_org_service')],
            },
        ),
    ]
