# Generated by Django 5.2.14 on 2026-09-12 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_import_history'),
        ('shifts', '0002_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='calculation_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DailyCalculation',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shifts.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.service')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='daily_calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='ledger.dailycalculation'),
        ),
        migrations.AddConstraint(
            model_name='dailycalculation',
            constraint=models.UniqueConstraint(fields=('service', 'organization', 'date'), name='ledger_daily_calculation'),
        ),
    ]
