# Generated by Django 5.2.14 on 2026-09-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_daily_calculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('artifact', models.BinaryField(default=bytes)),
                ('recipient', models.BigIntegerField()),
                ('state', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='earnings_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
