# Generated by Django 5.2.14 on 2026-09-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_earningsdelivery_settings_earnings_enabled'),
        ('shifts', '0002_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shifts.employee'),
        ),
    ]
