# Generated by Django 5.2.14 on 2026-09-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_accrual_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_state',
            field=models.CharField(choices=[('none', 'none'), ('open', 'open'), ('paid', 'paid'), ('superseded', 'superseded')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='organizationbilling',
            name='payment_recipients',
            field=models.ManyToManyField(blank=True, related_name='payment_organizations', to='ledger.telegramcontact'),
        ),
        migrations.CreateModel(
            name='PaymentMessageUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('state', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.invoice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipient', 'message_id'), name='ledger_payment_message_update')],
            },
        ),
    ]
