# Generated by Django 5.2.14 on 2026-09-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0007_invoice_payment_confirmation'),
        ('shifts', '0002_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('thread_id', models.BigIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfferDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=24)),
                ('recipient', models.BigIntegerField()),
                ('thread_id', models.BigIntegerField(null=True)),
                ('version', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=180, unique=True)),
                ('state', models.CharField(db_index=True, default='pending', max_length=16)),
                ('message_ids', models.JSONField(default=list)),
                ('prompt_key', models.CharField(blank=True, max_length=100)),
                ('reply_resolved', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(null=True)),
                ('error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OfferMessageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, default='pending', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(null=True)),
                ('error', models.TextField(blank=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offers.offerdelivery')),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('header_path', models.CharField(blank=True, max_length=200)),
                ('sample_path', models.CharField(blank=True, max_length=200)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('sample_error', models.TextField(blank=True)),
                ('sample_version', models.PositiveIntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shifts.organization')),
                ('publishers', models.ManyToManyField(blank=True, related_name='offer_profiles', to='ledger.telegramcontact')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=180, unique=True)),
                ('sender_id', models.BigIntegerField()),
                ('sender_name', models.CharField(blank=True, max_length=160)),
                ('source_signature', models.CharField(blank=True, db_index=True, max_length=64)),
                ('caption_message_id', models.BigIntegerField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('state', models.CharField(db_index=True, default='collecting', max_length=24)),
                ('employee_name', models.CharField(blank=True, max_length=160)),
                ('assignee_user_id', models.BigIntegerField(null=True)),
                ('intervals', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('topic_chat_id', models.BigIntegerField(null=True)),
                ('topic_thread_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('duplicate_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.shiftoffer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shifts.employee')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shifts.organization')),
            ],
        ),
        migrations.AddField(
            model_name='offerdelivery',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='offers.shiftoffer'),
        ),
        migrations.CreateModel(
            name='RecognitionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(db_index=True, default='pending', max_length=16)),
                ('available_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('elapsed_ms', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.recognitionprofile')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='offers.shiftoffer')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('offer__isnull', False), ('profile__isnull', True)), models.Q(('offer__isnull', True), ('profile__isnull', False)), _connector='OR'), name='recognition_one_target')],
            },
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('message_id', models.BigIntegerField()),
                ('telegram_file_id', models.TextField(blank=True)),
                ('recognized', models.JSONField(default=dict)),
                ('purged_at', models.DateTimeField(null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.shiftoffer')),
            ],
            options={
                'ordering': ('message_id', 'id'),
                'constraints': [models.UniqueConstraint(fields=('offer', 'message_id'), name='offer_source_image')],
            },
        ),
    ]
