# Generated by Django 5.2.14 on 2026-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerconfig',
            name='claimed_thread_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerconfig',
            name='released_thread_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdelivery',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerdelivery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdelivery',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offerdelivery',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='delivery_generation',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
