# Generated by Django 5.2.14 on 2026-09-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_invoice_payment_confirmation'),
        ('offers', '0002_topic_delivery_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='input_type',
            field=models.CharField(default='time', max_length=16),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='kind',
            field=models.CharField(db_index=True, default='shift', max_length=16),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.service'),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='service_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='update_mode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='update_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='offers.shiftoffer'),
        ),
        migrations.AddField(
            model_name='shiftoffer',
            name='update_target_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OfferWizard',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('step', models.CharField(default='source', max_length=24)),
                ('data', models.JSONField(default=dict)),
                ('processed_messages', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.shiftoffer')),
            ],
        ),
    ]
